# Generated by Django 4.2.10 on 2024-03-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0003_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Sem Marca', max_length=255),
        ),
    ]
