# Generated by Django 4.2.10 on 2024-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0005_listasaida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaSaida',
        ),
    ]
