# Generated by Django 4.2.10 on 2024-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0007_saida_itemsaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsaida',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
