# Generated by Django 4.2.10 on 2024-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0008_alter_itemsaida_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
