# Generated by Django 4.2.10 on 2024-05-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetointegradors', '0009_produto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsaida',
            name='preco_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
